//1)
//public class Helloworld {
  //  public static void main(String[] args) {
      //  System.out.print("hello world\nfrom sujal saraswat\non monday\nwhich is full of delightness and\nextravaganza.\ni want no one\nto disturb me during programming\nso that i could attempt focusing\non good things!\nat the end everything is gonna to be\nsort out with money and skiils\nso stay tuned on yiur own workd\nlike building new skiils\nand\ndeveloping a hard man's mindset\nin the era of\nold mans struggle!\nit is the era of artificial intelligence\nand a period of our country\nindia to become a superpower of this competetoive irrelevant world!\nonly private sector have that power of\nmaking our country proud and moneyfull and in private sector 90%\npof the power is in\nit sector's hand\nso be prepared all the software\nengineers to be a part\nof future building!");
   // }

   //2)
// public class Helloworld {
    //public static void main(String[] args) {
      //   int a = 12;
  // int b = 34;
  // int c = 78;
  // int d = 3456;
   //int e = 23;
  // int f = 56;
  // int g = 678;
  // int h = 342;
  // int i = 90;
  // int j = 1234;
  // int k = 120;
  // int l = 67;
  // int m = 697;
  // int n = 909;
 //  int o = 3333;
   //int p = 445;
   //int q = 667;
   //int r = 7686;
   //int s= 234;
   //int t = 456;
  // int u = 3452;
  // int v = 7890;
   //int w = 12345678;
  // int x = 111;
  // int y = 231;
  // int z = 980;
  // int a1 = (a + b + c + d + e + f + g + h + j + k + l) - (m + n + o + p + q + r + s + t + u + v + w + x + y + z) / (a + n + w + e + f + g + s + i);
  //System.out.println(a1);
   
   //}

   // }


//3)
 // import java.util.Scanner;
  
  // public class Helloworld {
   // public static void main(String[] args) {
        //input
       // Scanner sc = new Scanner(System.in);
       // int a = sc.nextInt();
        //int b = sc.nextInt();
        //int sum = a + b;
        //System.out.println("The sum of two integers a and b is :" + sum);
    
   // }
  // }

  //4)
  //import java.util.Scanner;
  
 // public class Helloworld {
   // public static void main(String[] args) {
     // Scanner sc = new Scanner(System.in);
     // int a = sc.nextInt();
     // int b = sc.nextInt();
     // int c = a + b;
     // System.out.println(c);

    //}
 // }

 //5)
 //To make a multiplication table of the number input by the user
 //import java.util.Scanner;

 //public class Helloworld {
 // public static void main(String[] args) {
   // Scanner sc = new Scanner(System.in);
   // int m = sc.nextInt();
    //loops
   // for(int i = 1; i <= 10; i = i + 1) {
    //  System.out.println(m * i);
   // }
 // }
// }

//6)
//using if/else statement foraddition.

//import java.util.Scanner;

//public class Helloworld {
 // public static void main(String[] args) {
   // Scanner sc = new Scanner(System.in);
    //int a = sc.nextInt();
   // int b = sc.nextInt();
    //conditions;
   // if(a > b) {
   //   System.out.println(a + b);
  //  }else {
    //  System.out.println(a * b);
   // }
  //}
//}

//7)
//using if/else statements for a large code.

//import java.util.Scanner;

//public class Helloworld {
  //public static void main(String[] args) {
   // Scanner sc = new Scanner(System.in);
   // int age = sc.nextInt();
    //conditions
   // if(age <= 1) {
    //  System.out.println("new born baby!💕");
  //  }else {
     // if(age <= 3) {
       // System.out.println("baby!😁!");
     // }else {
       // if(age <= 5) {
         // System.out.println("school going baby!!!");
       // }else {
         // if(age <= 8) {
           // System.out.println("growing child😍");
        //  }else {
           // if(age <= 12) {
             // System.out.println("child😘!");
           // }else {
             // if(age <= 14) {
                //System.out.println("young teenager😊");
              //}else {
               // if(age <= 18) {
                 // System.out.println("teenager😳");
               // }else {
                 // if(age <= 19) {
                   // System.out.println("elder teenager");
                 // }else {
                    //if(age <= 21) {
                     // System.out.println("adult👨🏼👨🏼👨🏼");
                   // }else {
                    //  if(age <= 25) {
                       // System.out.println("younger adult🤦🤷🤦");
                     // }else {
                      //  if(age <= 28) {
                         // System.out.println("growing adult!!!");
                       // }else {
                         // if(age <= 32) {
                           // System.out.println("adult🤣😂🤣😂");
                        //  }else {
                            //if(age <= 36) {
                             // System.out.println("older adult");
                           // }else {
                             // if(age <= 40) {
                               // System.out.println("uncle jii👪👪👪");
                             // }else {
                               // if(age <= 45) {
                                 // System.out.println("older uncle!!");
                               // }else {
                                 // if(age <= 55) {
                                  //  System.out.println("younger old🧓🏼");
                                 // }else {
                                  //  if(age <= 70) {
                                   //   System.out.println("old!!!");
                                  //  }else {
                                     // System.out.println("died");
                                   // }
                                //  }
                               // }
                            //  }
                           // }
                         // }
                       // }
                     // }
                   // }
                 // }
               // }
             // }
           // }
          //}
      //  }
    //  }
   // }
  //}
//}


//8)
//code for area of circle input by user;
//import java.util.Scanner;

//public class Helloworld {
 // public static void main(String[] args) {
   // Scanner sc = new Scanner(System.in);
   // int a = sc.nextInt();
    //int b = (22/7);
    //int c = b * (a * a);
    //System.out.println(c);
  //}
//}

//9)
//the multiplication table;
//import java.util.Scanner;

//public class Helloworld {
  //public static void main(String[] args) {
   // Scanner sc = new Scanner(System.in);
   // int a = sc.nextInt();
   // System.out.println("the multiplication table is:" );
   // System.out.println(a * 1);
   // System.out.println(a * 2);
   // System.out.println(a * 3);
   // System.out.println(a * 4);
   // System.out.println(a * 5);
   // System.out.println(a * 6);
  //  System.out.println(a * 7);
   // System.out.println(a * 8);
   // System.out.println(a * 9);
   // System.out.println(a * 10);

 // }
//}

//10)
//programme of odd even numbers;
//import java.util.Scanner;

//public class Helloworld {
  //public static void main(String[] args) {
   // Scanner sc = new Scanner(System.in);
   // int a = sc.nextInt();
   // if(a % 2 == 0) {
    //  System.out.println("even");
   // }else {
    //  System.out.println("odd");
   // }
//  }
//}

//11)
//code for comparison between and b;
//import java.util.Scanner;

//public class Helloworld {
 // public static void main(String[] args) {
 //   Scanner sc = new Scanner(System.in);
 //   int a = sc.nextInt();
 //   int b = sc.nextInt();
 //   if(a == b) {
 //     System.out.println("equal!");
 //   }else {
 //     if(a > b) {
 //       System.out.println("a is greater then b!");
  //    }else {
//        if(a < b) {
//          System.out.println("a is smaller than b!");
//        }
//      }
 //   }
  //}
//}

//12)
//code of else if statement;
//import java.util.Scanner;

//public class Helloworld {
 // public static void main(String[] args) {
    //input
 //   Scanner sc = new Scanner(System.in);
 //   int button = sc.nextInt();
 //   if(button == 1) {
 //     System.out.println("namastey!");
 //   }else if(button == 2) {
 //     System.out.println("hello!!!");
 //   }else if(button == 3) {
 //     System.out.println("bonjour");
 //   }else {
 //     System.out.println("invalid");
 //   }
//  }
//}



//LEAP YEAR PROGRAMME:
import java.util.*;
public class Main{
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        System.out.println("PLEASE ENTER A YEAR:");
        int year = sc.nextInt();
        if(year%400==0||year%4==0 && year%100!=0){
            System.out.println(year + " IS A LEAP YEAR");
        }
        else{
            System.out.println(year + " IS NOT A LEAP YEAR!");
        }
    }
}


//13)
//switch button code;

//import java.util.Scanner;

//public class Helloworld {
 // public static void main(String[] args) {
    //input
 //   Scanner sc = new Scanner(System.in);
 //   int button = sc.nextInt();
 //   switch(button) {
 //     case 1 : System.out.println("namastey!");
   //   break;
     // case 2 : System.out.println("sastriya kaal!!");
 //     break;
//      case 3 : System.out.println("adaab!!!");
//      break;
//      case 4 : System.out.println("jai hind!!!!");
//      break;
 //     case 5 : System.out.println("bharat mata ki jaiiiiiiiii");
 //     break;
//      default : System.out.println("invalid attempt");
//    }
 // }
//}

//14
//to make a calculator;
//import java.util.Scanner;

//public class Helloworld {
  //public static void main(String[] args) {
    //input
    //Scanner sc = new Scanner(System.in);
//    int a = sc.nextInt();
//    int b = sc.nextInt();
//    int button = sc.nextInt();
//    switch(button) {
 //     case 1 : System.out.println(a + b);
//      break;
//      case 2 : System.out.println(a - b);
 //     break;
 //     case 3 : System.out.println(a * b);
 //     break;
 //     case 4 : System.out.println(a / b);
//      break;
 //     case 5 : System.out.println(a % b);
//      break;
//      default : System.out.println("invalid attempt , error!!!");
//    }
//  }
//}

//15)
//import java.util.Scanner;

//public class Helloworld {
  //public static void main(String[] args) {
    //input
 //   Scanner sc = new Scanner(System.in);
 //   int a = sc.nextInt();
 //   int b = sc.nextInt();
 //   int button = sc.nextInt();
//    if(button == 1) {
 //     System.out.println(a + b);
//    }else if(button == 2) {
//      System.out.println(a - b);
  //  }else if(button == 3) {
 //     System.out.println(a * b);
 //   }else if(button == 4) {
 //     System.out.println(a / b);
//    }else if(button == 5) {
  //    System.out.println(a % b);
 //   }else {
 //     System.out.println("invalid attempt , try again later - eligator!!!");
   // }
 // }
//}

//16)
//code of weekdays

//import java.util.Scanner;

//public class Helloworld {
 // public static void main(String[] args) {
    //input
 //   Scanner sc = new Scanner(System.in);
//    int a = sc.nextInt();
  //  switch(a) {
    //  case 1 : System.out.println("sunday");
      //break;
   //   case 2 : System.out.println("monday");
 //     break;
     // case 3 : System.out.println("Tuesday");
 //     break;
   //   case 4 : System.out.println("wednesday");
     // break;
   //   //case 5 : System.out.println("thursday");
  //    break;
   //   case 6 : System.out.println("friday");
   //   break;
   //   case 7 : System.out.println("Saturday");
     // break;
  //    default : System.out.println("invalid attempt , just losttt!");
  //  }
//  }


//17)
//}code for months

//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
 //   Scanner sc = new Scanner(System.in);
 //   //input
 //   int a = sc.nextInt();
//    switch(a) {
//      case 1 : 
//      System.out.println("january");
//      break;
//      case 2 :
//       System.out.println("February");
//      break;
//      case 3 :
//      System.out.println("march");
//      break;
//      case 4 :
 //     System.out.println("april");
//      break;
//      case 5 : 
 //     System.out.println("may");
//      break;
//      case 6 :
//      System.out.println("june");
//      break;
//      case 7 :
//      System.out.println("july");
//      break;
//      case 8 :
//      System.out.println("august");
 //     break;
//      case 9 : 
 //     System.out.println("september");
 //     break;
 //     case 10 :
 //      System.out.println("october");
 //     break;
 //     case 11 :
//       System.out.println("November");
//      break;
 //     case 12 : 
 //     System.out.println("december");
//      break;
//      default :
//      System.out.println("invalid attempt , try again.");
//    }
//  }
//}


//18)
//multiplication table
//import java.util.Scanner;

//public class Helloworld {
  //public static void main(String[] args) {
    //input
    //Scanner sc = new Scanner(System.in);
    //int a = sc.nextInt();
    //loop
    //for(int i = 1; i <= 10; i++) {
      //System.out.println(a * i);
   // }
//  }
//}


//19)
//while loop
//public class Helloworld {
 // public static void main(String[] args) {
 //   int i = 0;
 //   while(i <= 10) {
 //     System.out.println(i);
 //     i++;
 //   }
//  }
//}


//20)
//do while loop
//public class Helloworld {
  //public static void main(String[] args) {
    //int i = 1;
    //do {
      //System.out.println(i);
      //i++;
    //}while(i <= 10);
  //}
//}


//21)
//multiplication table from do while loop;

//import java.util.Scanner;

//public class Helloworld {
  //public static void main(String[] args) {
    //input
    //Scanner sc = new Scanner(System.in);
    //int a = sc.nextInt();
    //int i = 1;
    //do {
      //System.out.println(a * i);
      //i++;
    //}while(i <= 10);

 // }
//}


//22)
//multiplication table from while loop;

//import java.util.Scanner;

//public class Helloworld {
  //public static void main(String[] args) {
    //input
    //Scanner sc = new Scanner(System.in);
    //int a = sc.nextInt();
    //while loop;
    //int i = 1;
    //while(i <= 10) {
      //System.out.println(a * i);
      //i++;
    //}
//}
//}



//23)
//programme to calculate number of letters in a sentence;
//import java.util.Scanner;

//public class Helloworld {
  //public static void main(String[] args) {
    //Scanner sc = new Scanner(System.in);
    //String name = sc.nextLine();
    //int b = name.Length();
    //System.out.println(b);
  //}
//} 



//24
//how to input float value
//import java.util.Scanner;

//public class Helloworld {
  //public static void main(String[] args) {
    //input
    //Scanner sc = new Scanner(System.in);
    //float a = sc.nextFloat();
    //float b = sc.nextFloat();
    //float c = sc.nextFloat();
    //System.out.println(c);
  //}
//}


//PROGRAMME TO CALCULATE POWER:
import java.util.Scanner;

public class dsa{
    public static void pow(int a , int b){
        double res = Math.pow(a, b);   //power fn
        System.out.println(res);
    }
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        System.out.println("Please enter a:");
        int c = sc.nextInt();
        System.out.println("Please enter b:");
        int d = sc.nextInt();
        System.out.println(c + " " + "KI POWER" + " " + d + " " + "=");
        pow(c,d);
    }
}


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// import java.util.Scanner;

// public class Main{
//     public static int sum(int a, int b){
//         return a+b;
//     }
//     public static void main(String args[]){
//         int sum = sum(10,11);
//         System.out.println(sum);
//     }
// }



--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

// import java.util.Scanner;

// public class Main{
//     public static void res(){
//         Scanner sc = new Scanner(System.in);
//         System.out.println("please enter a number:");
//         int num = sc.nextInt();
//         if(num%2==0){
//             System.out.println("its even!");
//         }
//         else{
//             System.out.println("odd!!");
//         }
//     }
//     public static void main(String args[]){
//         res();
//     }
// }

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



//TO PRINT SQUARE OF NUM INPUT BY USER:
import java.util.Scanner;

public class dsa{
    public static int square(int a){
        return a*a;
    }
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        System.out.println("PLEASE ENTER A NUMBER:");
        int num = sc.nextInt();
        System.out.println("THE SQUARE OF " + num + " IS:" + " " + square(num));
    }
}



//TO CHECK ODD OR EVEN:
import java.util.Scanner;

public class dsa{
    public static int checkNum(int a){
        if(a%2==0){
            System.out.println("even");
        }
        else{
            System.out.println("Odd");
        }
        return a;
    }
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        System.out.println("PLEASE ENTER A NUM:");
        int num = sc.nextInt();
        System.out.println("THE NUM" + " " + num + " " + "IS:");
        checkNum(num);
    }
}



//TO CALCULATE FACTORIAL:
import java.util.Scanner;

public class dsa{
    public static int fact(int a){
        int fact = 1;
        for(int i = 1; i <= a; i++){
            fact = fact * i;
        }
        return fact;
    }
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        System.out.println("PLEASE ENTER A NUM:");
        int num = sc.nextInt();
        int res = fact(num);
        System.out.println(res);
    }
}



//check biggest num:
import java.util.Scanner;

public class dsa{
    public static void big(int a, int b){
        if(a>b){
            System.out.println(a + " " + "IS GREATER THAN" + " " + b);
        }
        else if(b>a){
            System.out.println(b + " " + "IS GREATER THAN" + " " + a);
        }
        else{
            System.out.println("BOTH ARE EQUAL.");
        }
    }
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        System.out.println("PLEASE ENTER A:");
        int c = sc.nextInt();
        System.out.println("PLEASE ENTER B:");
        int d = sc.nextInt();
        big(c,d);

    }
}



//PROGRAMME TO CALCULATE POWER:
import java.util.Scanner;

public class dsa{
    public static void pow(int a , int b){
        double res = Math.pow(a, b);   //power fn
        System.out.println(res);
    }
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        System.out.println("Please enter a:");
        int c = sc.nextInt();
        System.out.println("Please enter b:");
        int d = sc.nextInt();
        System.out.println(c + " " + "KI POWER" + " " + d + " " + "=");
        pow(c,d);
    }
}


//INPUT IN ARRAYS:
import java.util.*;

public class dsa{
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        //input for array size:
        int arr[] = new int[n];
        System.out.println("THE SIZE OF ARRAY IS" + " " + n);
        System.out.println("please enter elements in array:");
        for(int i = 0; i < n; i++){
            arr[i] = sc.nextInt();
        }
        for(int i = 0; i < n; i++){
            System.out.println(arr[i]);
        }
        // System.out.println("THE ARRAY IS:" + " " + "[" + arr[0] + "," + arr[1] + "]");
    }
}



//PROGRAMME TO SELECT EVEN/ODD VALUES IN ARRAY ACC TO INPUT BY USER:
import java.util.Scanner;
public class dsa{
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        int arr[] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30};
        System.out.println("WHAT DO YOU WANT?? EVEN OR ODD... FROM THE ARRAY:");
        for(int i = 0; i < arr.length; i++){
            System.out.print(arr[i] + " ");
        }
        System.out.println("PLEASE ENTER:");
        String type = sc.nextLine();
        if(type.equals("even")){
            for(int i = 0; i < arr.length; i++){
                if(arr[i]%2==0){
                    System.out.print(arr[i] + " ");
                }
            }
        }
        else if(type.equals("odd")){
            for(int i = 0; i < arr.length; i++){
                if(arr[i]%2!=0){
                    System.out.print(arr[i] + " ");
                }
            }
        }
        else{
            System.out.println("WRONG INPUT..");
        }
    }
}


//25
//programe of input by user in functions and methods;

//import java.util.Scanner;

//public class Helloworld {
//  public static int sujal(int a , int b) {
//    int c;
//    if(a > b) {
//      c = a + b;
//      System.out.println(c);
//    }else {
//      c = (a + b) * 12;
//      System.out.println(c);
//    }
//    return c;
//  }
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    int a = sc.nextInt();
//    int b = sc.nextInt();
//   int c = sujal(a , b);
//    System.out.println("the sum of a and b is:");
//    System.out.print(c);
//    int a1 = sc.nextInt();
//    int b1 = sc.nextInt();
//    int c1 = sujal(a1 , b1);
//    System.out.println("the sum of a1 and b1 is:");
//    System.out.print(c1);
//    int a2 = sc.nextInt();
//    int b2 = sc.nextInt();
//    int c2 = sujal(a2 , b2);
//    System.out.println("the sum of a2 and b2 is:");
//    System.out.print(c2);
//    int a3 = sc.nextInt();
//    int b3 = sc.nextInt();
//    int c3 = sujal(a3 , b3);
//    System.out.println("the sum of a3 and b3 is:");
//    System.out.println(c3);
//    int a4 = sc.nextInt();
//    int b4 = sc.nextInt();
//    int c4 = sujal(a4 , b4);
//    System.out.println("the sum of a4 and b4 is:");
//    System.out.print(c4);
//    int a5 = sc.nextInt();
//    int b5 = sc.nextInt();
//    int c5 = sujal(a5 , b5);
//    System.out.println("the sum of a5 and b5 is:");
//    System.out.print(c5);
//    int a6 = sc.nextInt();
//    int b6 = sc.nextInt();
//    int c6 = sujal(a6 , b6);
//    System.out.println("the sum of a6 and b6 is:");
//    System.out.print(c6);
//  }
//}


//26
//code for sum of two number input by user in functiions and methods;

//import java.util.Scanner;

//public class Helloworld {
//  public static int sum(int a , int b) {
//    int c = a + b;
//    return c;
//  }
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    int a = sc.nextInt();
//    int b = sc.nextInt();
//    int c = sum(a , b);
//    System.out.println("The sum is:");
//    System.out.print(c);
//  }
//}


//27
//programme to multiply two numbers input by user in functions and methods;

//import java.util.Scanner;

//public class Helloworld {
  //public static int product(int a , int b) {
    //int c = a * b;
    //return c;
 // }
 //public static void main(String[] args) {
  //Scanner sc = new Scanner(System.in);
  //int a = sc.nextInt();
  //int b = sc.nextInt();
  //int c = product(a , b);
  //System.out.println("the product is:");
  //System.out.println(c);
// }
//}

//----------------------------------------------------------------------------------------------------------------------------------------------------------------------
import java.util.Scanner;

public class Main{
    public static String name(String a, String b){
        String name3 = a;
        String name4 = b;
        String name5 = name3 + " " + name4;
        System.out.println("Your name is:" + " " + name5);
        return a+b;
    }
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        System.out.println("Please enter first name:");
        String name1 = sc.nextLine();
        System.out.println("Please enter last name:");
        String name2 = sc.nextLine();
        name(name1,name2);
    }
}



// import java.util.Scanner;

// public class Main{
//     public static String[] name(String a, String b){
//         System.out.println("Your paragraphs are:");
//         String para3 = a;
//         String para4 = b;
//         System.out.println(para3);
//         System.out.println(para4);
//         return new String[]{a,b};     
    
//     }
//     public static Long[] num(Long a, Long b, Long c, Long d){
//         Long num1 = a;
//         Long num2 = b;
//         Long num3 = c;
//         Long num4 = d;
//         System.out.println("Your phone numbers are:");
//         System.out.println(num1);
//         System.out.println(num2);
//         System.out.println(num3);
//         System.out.println(num4);
//         return new Long[]{a,b,c,d};
//     }
//     public static double[] dec(double a,double b,double c,double d){
//         System.out.println("Your values are:");
//         double val1 = a;
//         double val2 = b;
//         double val3 = c;
//         double val4 = d;
//         System.out.println((double)val1);
//         System.out.println((double)val2);
//         System.out.println((double)val3);
//         System.out.println((double)val4);
//         return new double[]{a,b,c,d};
//     }
//     public static void main(String args[]){
//         Scanner sc = new Scanner(System.in);
//         System.out.println("Please enter para1:");
//         String para1 = sc.nextLine();
//         System.out.println("Please enter para2:");
//         String para2 = sc.nextLine();
//         name(para1,para2);
//         //---------------------------------------------------------------------------------------
//         System.out.println("Please enter phone numbers:");
//         System.out.println("Please enter first number:");
//         Long num1 = sc.nextLong();
//         System.out.println("Please enter second number:");
//         Long num2 = sc.nextLong();
//         System.out.println("Please enter third number:");
//         Long num3 = sc.nextLong();
//         System.out.println("Please enter fourth number:");
//         Long num4 = sc.nextLong();
//         num(num1,num2,num3,num4);
//         //-------------------------------------------------------------------------------------
//         System.out.println("Please enter decimal values:");
//         System.out.println("Please enter first value:");
//         double val1 = sc.nextDouble();
//         System.out.println("Please enter second value:");
//         double val2 = sc.nextDouble();
//         System.out.println("Please enter third value:");
//         double val3 = sc.nextDouble();
//         System.out.println("Please enter fourth value:");
//         double val4 = sc.nextDouble();
//         dec(val1,val2,val3,val4);
//     }
// }




//28
//issue of skipping next line:
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    int a = sc.nextInt();
//    double b = sc.nextDouble();
//    sc.nextLine();
//    String name = sc.nextLine();
//    //output
//    System.out.println(name);
//    System.out.println(b);
//    System.out.print(a);
//  }
//}



//29
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    System.out.println("enter the first number:");
//    int a = sc.nextInt();
//    System.out.println("enter the second number:");
//    int b = sc.nextInt();
//    System.out.println("the product of both the numbers is:");
//    int c = a * b;
//    System.out.println(c);
//    //result;
//  }
//}



//30
//arrays;
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    int[] marks = new int[3];
//    System.out.println("enter physics marks:");
//    marks[0] = sc.nextInt();
//    System.out.println("enter chemistry marks:");
//    marks[1] = sc.nextInt();
//    System.out.println("enter maths marks:");
//    marks[2] = sc.nextInt();
//    System.out.println("physics marks are:" + " " + marks[0]);
//    System.out.println("chemistry marks are:" + " " + marks[1]) ;
//    System.out.println("maths marks are:" + " " + marks[2]);
//  }
//}



//31
//public class Helloworld {
//  public static void main(String[] args) {
//    int[] marks = new int[7];
//    marks[0] = 56;
//    marks[1] = 89;
//    marks[2] = 91;
//    marks[3] = 34;
//    marks[4] = 93;
//    marks[5] = 95;
//    marks[6] = 98;
//    marks[7] = 78;
//    for(int i = 0; i < 7; i++) {
//      System.out.println(marks[i]);
//    }
//  }
//}



//32
//public class Helloworld {
//  public static void main(String[] args) {
//    int marks[] = {97 , 90 , 78 , 87 , 89 , 93 , 74 , 91 , 67 , 83 , 81 , 92 , 77 , 98};
//    for(int i = 0; i < 14; i++) {
//      System.out.println(marks[i]);
// }
//  }
//}



import java.util.Scanner;

public class Main{
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        int[] arr = new int[3];
        System.out.println("Please enter physics marks:");
        arr[0] = sc.nextInt();
        System.out.println("Please enter chemistry marks:");
        arr[1] = sc.nextInt();
        System.out.println("Please enter maths marks:");
        arr[2] = sc.nextInt();
        System.out.println("PHYSICS = " + arr[0]);
        System.out.println("CHEMISTRY = " + arr[1]);
        System.out.println("MATHS = " + arr[2]);
        int res = (arr[0]+arr[1]+arr[2]);
        System.out.println("TOTAL = " + res + " OUT OF 300!");
    }
}




//33
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    System.out.println("enter the number of elements-");
//    int size = sc.nextInt();
//    int marks[] = new int[size];
//    for(int i = 0; i < size; i++) {
//      marks[i] = sc.nextInt();

//    }
//    for(int i = 0; i < size; i++) {
//      System.out.println(marks[i]);
//    }
//  }
//}


//34
//public class Helloworld {
//  public static void main(String[] args) {
//    int[] marks = new int[10];
//    marks[0] = 67;
//    marks[1] = 74;
//    marks[2] = 81;
//    marks[3] = 87;
//    marks[4] = 92;
//    marks[5] = 91;
//    marks[6] = 82;
//    marks[7] = 98;
//    marks[8] = 75;
//    marks[9] = 77;
//    for(int i = 0; i < 10; i++) {
//      System.out.println(marks[i]);
//    }

//  }
//}



//35
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    int marks[] = new int[6];
//    marks[0] = sc.nextInt();
//    marks[1] = sc.nextInt();
//    marks[2] = sc.nextInt();
//    marks[3] = sc.nextInt();
//    marks[4] = sc.nextInt();
//    marks[5] = sc.nextInt();
//    System.out.println("the marks are:");
//    for(int i = 0; i < 6; i++) {
      
//      System.out.println(marks[i]);
//    }
//  }
//}



//36
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    int size = sc.nextInt();
//    String[] names = new String[size];
//    for(int i = 0; i < size; i++) {
//      names[i] = sc.next();
//    }
//    for(int i = 0; i< size; i++) {
//      System.out.println(names[i]);
//    }
//  }
//}



//2-D Arrays;
//37
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    int rows = sc.nextInt();
//    int columns = sc.nextInt();
//    int[][] numbers = new int[rows][columns];
//    for(int i = 0; i < rows; i++) {
//      for(int j = 0; j < columns; j++) {
//        numbers[i][j] = sc.nextInt();
//     }
//    }
//    for(int i = 0; i < rows; i++) {
//      for(int j = 0; j < columns; j++) {
//        System.out.print(numbers[i][j] + " ");
//      }
//      System.out.println();
//    }
//    }
//  }




//code to find out number entered by user in rows and columns (2D arrays);
//38
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    int rows = sc.nextInt();
//    int columns = sc.nextInt();
//    int[][] numbers = new int[rows][columns];
//    //this is for input of numbers by the user;
//    for(int i = 0; i < rows; i++) {
//      for(int j = 0; j < columns; j++) {
//        numbers[i][j] = sc.nextInt();
//      }
//    }
//    //input of number x by the user:
//    int x = sc.nextInt();
//    //to print the number;
//    for(int i = 0; i < rows; i++) {
//      for(int j = 0; j < columns; j++) {
//        if(numbers[i][j] == x) {
//          System.out.println("x is found on:" + "(" + i + "," + j + ")");
//        }
//      }
//    }
//  }
//}




//transpose of rows and columns in 2D arrays{row ki jagah column , column ki jagah row}
//39
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    int rows = sc.nextInt();
//    int columns = sc.nextInt();
//    int[][] numbers = new int[rows][columns];
//    for(int i = 0; i < rows; i++) {
//      for(int j = 0; j < columns; j++) {
//        numbers[i][j] = sc.nextInt();
//      }
//    }
//    System.out.println("the transpose is:");
//    for(int j = 0; j < columns; j++) {
//      for(int i = 0; i < rows; i++) {
//        System.out.print(numbers[i][j] + " ");


//      }
//      System.out.println();
//    }
//  }
//} 



//sum of integers in array
//40
//public class Helloworld {
  //public static void main(String[] args) {
    //int[] sum = new int[5];
    //sum[0] = 56;
    //sum[1] = 90;
    //sum[2] = 92;
    //sum[3] = 98;
    //sum[4] = sum[0] + sum[1] + sum[2] +sum[3];
    //System.out.println(sum[4]);
 // }
//}



//sum of numbers input by user in arrays;
//41
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    int[] sum = new int[5];
//    sum[0] = sc.nextInt();
//    sum[1] = sc.nextInt();
//    sum[2] = sc.nextInt();
//    sum[3] = sc.nextInt();
//    sum[4] = sum[0] + sum[1] + sum[2] + sum[3];
//    System.out.println("the sum is:");
//    System.out.println(sum[4]);
  
//  }
//}



//programme to find average in arrays;
//42
//public class Helloworld {
//  public static void main(String[] args) {
//    int[] min = new int[10];
//    min[0] = 45;
//    min[1] = 50;
//    min[2] = 55;
//    min[3] = 56;
//    min[4] = 67;
//    min[5] = 77;
//    min[6] = 90;
//    min[7] = 91;
//    min[8] = 900;
//    min[9] = (min[0] + min[1] + min[2] + min[3] + min[4] + min[5] + min[6] + min[7] + min[8]) / 9;
//    System.out.println(min[9]);
//  }
//}




//programme to print values in 2D arrays;
//43
//public class Helloworld {
  //public static void main(String[] args) {
//    int[][] sum = new int[3][3];
//    sum[0][0] = 78;
//    sum[0][1] = 90;
//    sum[0][2] = 33;
//    sum[1][0] = 56;
//    sum[1][1] = 99;
//    sum[1][2] = 78;
//    sum[2][0] = 98;
//    sum[2][1] = 90;
//    sum[2][2] = 67;
//    for(int i = 0; i < 3; i++) {
//      for(int j = 0; j < 3; j++) {
//        System.out.println(sum[i][j]);
//      }
//    }
//  }
//}



//programme to print sum of elements of row and columns in 2D arrays;
//44
//import java.util.Scanner;
//public class Helloworld {
//  public static void main(String[] args) {
//    
//Scanner sc = new Scanner(System.in);
//    int[][] sum = new int[2][2];
//    sum[0][0] = sc.nextInt();
//    sum[1][0] = sc.nextInt();
//    sum[0][1] = sc.nextInt();
//    sum[1][1] = sc.nextInt();
//    System.out.println("the sum is:");
//    int a = (sum[0][0] + sum[1][0] + sum[0][1] + sum[1][1]);
//        System.out.println(a);
//      }

  //}



  //programme of advance if else statements;
  //45
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    int n = sc.nextInt();
//    if(n % 2 == 1) {
//      System.out.println("Weird");
//    }else if(n >= 2 && n <= 5) {
//      System.out.println("Not Weird");
//    }else if(n >= 6 && n <= 20) {
//      System.out.println("Weird");
//    }else {
//      System.out.println("Not Weird");
//    }
//    }

//  }



//to calculate length of string;
//46
//public class Helloworld {
  //public static void main(String[] args) {
    //String name = sujal;
    //String name2 = saraswat;
    //String name3 = name + " " + name2;
    //System.out.println(name3.length);
 // }
//}





//to use charAt function of strings;
//47
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    String name = sc.nextLine();
//    String name2 = sc.nextLine();
//    String name3 = name + " " + name2;
//    System.out.println(name3.length());
//    for(int i = 0; i < name3.length(); i++) {
//      System.out.println(name3.charAt(i));
//    }
//  }
//}




//programme of substring of a string;
//48
//public class Helloworld {
  //public static void main(String[] args) {
    //String name = "my name is sujal";
    //String name2 = name.substring(11 , 16);
    //System.out.println(name2);
 // }
//}




//programme to compare two strings;
//49
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    String name = sc.nextLine();
//    String name2 = sc.nextLine();
//    if(name.compareTo(name2) == 0) {
//      System.out.println("equal");
//    }else {
//      System.out.println("not equal");
//    }
//  }
// }





//substring input from user;
//50
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String[] args) {
//    Scanner sc = new Scanner(System.in);
//    String name = sc.nextLine();
//    String name1 = sc.nextLine();
//    String name2 = name + " " + name1;
//    System.out.println(name2.length());
//    int i = sc.nextInt();
//    int j = sc.nextInt();
//    String name3 = name2.substring(i , j);
//    System.out.println(name3);
//  }
//}




//string builder decleration;
//51
//public class Helloworld {
  //public static void main(String[] args) {
    //StringBuilder sb = new StringBuilder("sujal saraswat");
    //System.out.println(sb);
//  }
//}





//to print a single character from a string in stringbuilder;
//52
//public class Helloworld {
  //public static void main(String args[]) {
    //StringBuilder sb = new StringBuilder("sujal saraswat");
    //System.out.println(sb.charAt(index number));
// }
//}






 //set char at index;
 //53
 //public class Helloworld {
//public static void main(String[] args) {
  //StringBuilder sb = new StringBuilder("daman");
  //sb.setCharAt(0 , 'n');
  //System.out.println(sb);
//}
 //}





//to insert a character in a string;
//54
//public class Helloworld {
  //public static void main(String[] args) {
    //StringBuilder sb = new StringBuilder("sujal");
    //sb.insert(0 , 's');
    //System.out.println(sb);
//  }
//}




//to delete a character in a string;
//55
//public class Helloworld {
  //public static void main(String args[]) {
    //StringBuilder sb = new StrinBuilder("sujal");
    //sb.delete(0 , 1);
    //System.out.println(sb);
//  }
//}




//to add extra string at the end of a string;
//56
//public class Helloworld {
  //public static void main(String args[]) {
    //StringBuilder sb = new StringBuilder("tony");
    //sb.append(" stark");
    //System.out.println(sb);
  //  }
//}





//input programme in charAt function of stringbuilder;
//57
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String args[]) {
//    Scanner sc = new Scanner(System.in);
//    StringBuilder sb = new StringBuilder("my name is sujal saraswat");
//    int a = sc.nextInt();
//    for(int i = 0; i < a; i++) {
//      System.out.println(sb.charAt(i));
//    }
//  }
//}





//input programme fot insert of character in stringbuilder;
//58
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String args[]) {
//    Scanner sc = new Scanner(System.in);
//    StringBuilder sb = new StringBuilder("namo namah om deva!");
//    int a = sc.nextInt();
//    String b = sc.next();
//    sb.insert(b , a);
//    System.out.println(sb);
//  }
//}





//input programme for delete function in setbuilder;
//59
//import java.util.Scanner;

//public class Helloworld {
//  public static void main(String args[]) {
//    StringBuilder sb = new StringBuilder("my name is anthony gonsalvis main duniya main akela hoon!");
//    Scanner sc = new Scanner(System.in);
//    int a = sc.nextInt();
//    int b = sc.nextInt();
//    sb.delete(a , b);
//    System.out.println(sb);

//  }
//}





//input programme of append;
//60
//import java.util.Scanner;

//public class Helloworld {
  //public static void main(String args[]) {
    //Scanner sc = new Scanner(System.in);
    //StringBuilder sb = new StringBuilder("tony");
    //String a = sc.nextLine();
    //sb.append(a);
    //System.out.println(sb);
//  }
//}

 


//length function of setbuilder;
//61
//public class Helloworld {
  //public static void main(String args[]) {
    //StringBuilder sb = new StringBuilder("naman");
    //System.out.println(sb.length());
//  }
//}









